# Copyright 2024 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "backend.conf"

# This is the main configuration file for the application.
# ~~~~~

appName = api-platform-deskpro

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Play Modules
play.modules.enabled += "uk.gov.hmrc.apiplatformdeskpro.config.Module"
play.modules.enabled += "uk.gov.hmrc.mongo.play.PlayMongoModule"
play.modules.enabled += "uk.gov.hmrc.internalauth.client.modules.InternalAuthModule"

# The application languages
# ~~~~~
play.i18n.langs = ["en"]

# Router
# ~~~~~
# Define the Router object to use for this application.
# This router will be looked up first when the application is starting up,
# so make sure this is the entry point.
# Furthermore, it's assumed your route file is named properly.
# So for an application router like `my.application.Router`,
# you may need to define a router file `conf/my.application.routes`.
# Default to Routes in the root package (and conf/routes)
# !!!WARNING!!! DO NOT CHANGE THIS ROUTER
play.http.router = prod.Routes

# Controller
# ~~~~~
# By default all controllers will have authorisation, logging and
# auditing (transaction monitoring) enabled.
# The below controllers are the default exceptions to this rule.



# Microservice specific config

deskpro {
  uri = "https://apiplatformsupporttest.deskpro.com"
  api-key  = "USE LOCAL ENV DESKPRO_KEY"
  brand = 3
  api-name = "6"
  support-reason = "7"
  reason-key = "11"
  organisation = "8"
  application-id = "9"
  team-member-email = "10"
  inactive = "5"
  inactivated-date = "4"
  referrer = "13"
  service = "14"
  session-id = "15"
  user-agent = "16"
  organisation-submission-id = "17"
}

mongodb {
  uri = "mongodb://localhost:27017/api-platform-deskpro"
}

importUser {
    initialDelay=10s
    interval=6h
    enabled=false
    deskpro-batch-size=1
    deskpro-batch-pause=500
    initial-import = true
}

deskpro-person-cache {
    timeout=24h
}

microservice {
  services {
    auth {
      host = localhost
      port = 8500
    }

    third-party-developer {
      host = localhost
      port = 9615
    }

    internal-auth {
      host = localhost
      port = 8470
    }
  }
}

